# DO LOGIN #
POST http://localhost:3000/session  HTTP/1.1
Content-Type: application/json

{
    "name": "livio"
}

###

# DO LOGIN #
POST http://localhost:3000/session  HTTP/1.1
Content-Type: application/json

{
    "name": "marzio"
}

###

# DO LOGIN #
POST http://localhost:3000/session  HTTP/1.1
Content-Type: application/json

{
    "name": "della"
}

###

# DO LOGIN #
POST http://localhost:3000/session  HTTP/1.1
Content-Type: application/json

{
    "name": "pippo"
}

###

# DO LOGIN #
POST http://localhost:3000/session  HTTP/1.1
Content-Type: application/json

{
    "name": "pluto"
}

###

# SET USERNAME #
PUT http://localhost:3000/users/1/name  HTTP/1.1
Authorization: 1
Content-Type: text/plain

penna

###

# GET USERS #
GET http://localhost:3000/users/1/others?srcName=o HTTP/1.1
Authorization: 1

###

# SET PICTURE #
PUT http://localhost:3000/users/1/image HTTP/1.1
Authorization: 1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="image.jpeg"
Content-Type: image/jpeg

< ./image.jpg

------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

# CREATE PRIVATE CONVERSATION #
POST http://localhost:3000/users/1/conversations/private?rcvId=2 HTTP/1.1
Authorization: 1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="text"

prova
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="image.jpeg"
Content-Type: image/jpeg

< ./image.jpg

------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

# CREATE PUBLIC CONVERSATION #
POST http://localhost:3000/users/1/conversations/group HTTP/1.1
Authorization: 1
Content-Type: application/json

{
    "name": "figata",
    "participants": [
        {
            "name": "marzio"
        },
        {
            "name": "della"
        }
    ]
}

###

# CREATE PRIVATE CONVERSATION #
POST http://localhost:3000/users/1/conversations/private?rcvId=3 HTTP/1.1
Authorization: 1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="text"
Content-Type: text/plain

prova
------WebKitFormBoundary7MA4YWxkTrZu0gW--


###

# GET CONVERSATIONS #
GET http://localhost:3000/users/1/conversations?srcName=a HTTP/1.1
Authorization: 1

###

# GET CONVERSATION #
GET http://localhost:3000/users/2/conversation/1 HTTP/1.1
Authorization: 2

###

# ADD TO GROUP #
POST http://localhost:3000/users/2/conversation/2 HTTP/1.1
Authorization: 2
Content-Type: application/json

[
    {
        "name": "pippo"
    },
    {
        "name": "pluto"
    }
]

###

# LEAVE GROUP #

DELETE http://localhost:3000/users/2/conversation/2 HTTP/1.1
Authorization: 2

###

# SET GROUP NAME #
PUT http://localhost:3000/users/1/conversation/2/name  HTTP/1.1
Authorization: 1
Content-Type: text/plain

pazzurdo

###

# SET GROUP PICTURE #
PUT http://localhost:3000/users/1/conversation/2/image HTTP/1.1
Authorization: 1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="image.jpeg"
Content-Type: image/jpeg

< ./image.jpg

------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

# SEND FULL MESSAGE TO PRIVATE #
POST http://localhost:3000/users/1/conversation/1/messages HTTP/1.1
Authorization: 1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="text"
Content-Type: text/plain

ciao
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="image.jpeg"
Content-Type: image/jpeg

< ./image.jpg

------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

# RESPOND TO MESSAGE #
POST http://localhost:3000/users/1/conversation/1/messages?responseTo=1 HTTP/1.1
Authorization: 1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="text"

risposta
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="image.jpg"
Content-Type: image/jpeg

< ./image.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

# SEND FULL MESSAGE TO GROUP #
POST http://localhost:3000/users/1/conversation/2/messages HTTP/1.1
Authorization: 1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="text"

ciao
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="image.jpeg"
Content-Type: image/jpeg

< ./image.jpg

------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

# RESPOND TO MESSAGE #
POST http://localhost:3000/users/1/conversation/2/messages?responseTo=1 HTTP/1.1
Authorization: 1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="text"

risposta
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

# FORWARD MESSAGE #
POST http://localhost:3000/users/1/conversation/1/messages/2 HTTP/1.1
Authorization: 1
Content-Type: application/json

[
    1
]

###

# DELETE MESSAGE #
DELETE http://localhost:3000/users/1/conversation/1/messages/1 HTTP/1.1
Authorization: 1

###

# COMMENT MESSAGE #
POST http://localhost:3000/users/2/conversation/1/messages/1/reactions HTTP/1.1
Authorization: 2
Content-Type: text/plain

😅

###

# UPDATE COMMENT MESSAGE #
POST http://localhost:3000/users/2/conversation/1/messages/1/reactions HTTP/1.1
Authorization: 2
Content-Type: text/plain

😁

###

# DELETE COMMENT MESSAGE #
DELETE http://localhost:3000/users/1/conversation/1/messages/1/reactions HTTP/1.1
Authorization: 1

###